import { Providers } from '@/shared/config/Providers';
import { manrope } from '@/shared/styles/fonts';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={manrope.variable}>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
